### ISSUE TITLE
Can you please do a camera tutorial 

### ISSUE THREAD

**Issue by levonravel** [opentk/LearnOpenTK#1]
I am having a hard time with it.. Using OpenGL4 - Thank you

**Comment by DylanFPS** [comment]
Don't worry, @devvoid will get round to it at some point. It's definitely on our list!

In the meantime, you can look at the camera tutorial at learnopengl.com and just translate the C code to C# - shouldn't be too difficult I hope.

**Comment by levonravel** [comment]
Yes I can convert that over without an issue.

**Comment by DylanFPS** [comment]
Awesome, I'll mark this issue as resolved then :)

**Comment by levonravel** [comment]
`    public class SceneCamera
    {
        private Matrix4 _proj;
        private Matrix4 _view;
        private int _prog;

        public void Start(GLControl control, int program)
        {
            _prog = program;
            _proj = Matrix4.CreatePerspectiveFieldOfView(1.5F, control.Width / control.Height, 0.01F, 1000);
            _view = Matrix4.LookAt(new Vector3(0, -10, 0), Vector3.Zero, new Vector3(0, 1, 0));            
            GL.UseProgram(_prog);    
        }

        public void Update()
        {           
            int viewLoc = GL.GetUniformLocation(_prog, "view");
            GL.UniformMatrix4(viewLoc, true, ref _view);

            int projLoc = GL.GetUniformLocation(_prog, "projection");
            GL.UniformMatrix4(projLoc, true, ref _proj);
        }
    }`

The problem isnt converting the code over but my camera wont display my model after moving it up along the Y axis.

**Comment by devvoid** [comment]
Will try to get to it soon! I'm busy with schoolwork now, but I should hopefully get to it within the near future.

**Comment by levonravel** [comment]
Thank you guys for your time. Really appreciate it, if I figure this out before the tutorial I could paste my code here in a simple to follow format with explanations. -Levon

**Comment by frederikja163** [comment]
I know this is a bit old, but i wanted to update you, i started working on it and i hope it is going to be done by today. (Not the web version, just the source code)
