### ISSUE TITLE
Change of namespace

### ISSUE THREAD

**Issue by ITALIA195** [opentk/LearnOpenTK#11]
The current namespace (LearnOpenGL_TK) does not match the github repository and does not make a lot of sense (LearnOpenGL_ToolKit?).

I think the namespace should be changed to LearnOpenTK

**Comment by Perksey** [comment]
> I think the namespace should be renamed to LearnOpenTK

Agreed

**Comment by devvoid** [comment]
I thought I'd done this a while back, will do in just a moment.

**Comment by devvoid** [comment]
Done and changed!
