### ISSUE TITLE
ImageSharp textures not working

### ISSUE THREAD

**Issue by teatwig** [opentk/LearnOpenTK#18]
Trying to run a Project using the Texture class results in the following exception:

> System.IO.FileLoadException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  at at LearnOpenTK.Common.Texture..ctor(String path)
  at at LearnOpenTK.Window.OnLoad(EventArgs e)
  at at OpenTK.GameWindow.OnLoadInternal(EventArgs e)
  at at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
  at at OpenTK.GameWindow.Run(Double updateRate)
  at at LearnOpenTK.Program.Main(String[] args)

This seems to be a problem with ImageSharp. I'm currently using the old Texture class with System.Drawing instead which is working fine.

**Comment by ITALIA195** [comment]
Try to delete all `bin` and `obj` folders in every project and see if it fixes

**Comment by teatwig** [comment]
Tried that without any difference.
Opened the solution in Visual Studio after that (I normally use Rider) and it the dependencies weren't imported. Running a `dotnet restore` in the folder fixed it for me.
