### ISSUE TITLE
A few tutorials I would like to see..

### ISSUE THREAD

**Issue by Shadowblitz16** [opentk/LearnOpenTK#42]
- Centered Orthographics camera
- Topleft Projection camera
- TopLeft Orthographics camera
- Scaling up vertices and uvs to pixel coordinates
- Custom 2D Drawing functions
- Custom 3D Drawing functions

**Comment by NogginBops** [comment]
These are not the types of tutorial we are aiming to create here. These different versions of nearly identical tutorial things would just make people copy the code without understanding any of it. We don't aim to be a copy paste resources, but a good learning resource.

Stuff like different versions of orthographic projections are for the programmer to figure out (sorry if this isn't the answer you want to hear, but learning matrices is just that useful).

The custom drawing functions is also a very subjective abstraction of the opengl API and should also be up to the programmer to design and implement.

You can definitely discuss your ideas and problems in the opentk discord, but I wouldn't hope for these kinds of tutorials.

https://learnopengl.com and [essence of linear algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) are great learning resources for these types of topics.

**Comment by Shadowblitz16** [comment]
ok
