### ISSUE TITLE
The name 'CursorGrabbed' does not exist in the current context

### ISSUE THREAD

**Issue by mrmsbarnes** [opentk/LearnOpenTK#46]
When I try to build the latest LearnOpenTK, I get the subject error.  Line 113 of Chapter1\8-Camera\Window.cs.  The assignment
    CursorVisible = false;
on line 112 has no error.

**Comment by NogginBops** [comment]
@mrmsbarnes this should be fixed in the latest version of this repository.

**Comment by mrmsbarnes** [comment]
Thank you.  All is well again.
