### ISSUE TITLE
Where can I find examples for ES20?

### ISSUE THREAD

**Issue by marcussacana** [opentk/LearnOpenTK#82]
Hi! I'm limited in the GL version due the old platform that I want to run the program, I have zero experience with OpenGL so I'm already stuck in the example 2 that use Shaders that can't be compiled in the ES20 and functions that aren't avaiable too, is there any example, maybe a working project, using OpenTK for ES2.0?

**Comment by NogginBops** [comment]
We do not provide any opengl es 2 samples.
However you can follow other tutorials for opengl es 2 and just change the function calls into the `GL.SomeFunc` format.

**Comment by marcussacana** [comment]
Thx, I still in the triangle level, then too early to doubts, I will comment here If I get one later :)
