### ISSUE TITLE
Resizing window on MacOS doesn't take care of the scale factor*2

### ISSUE THREAD

**Issue by DigitalBox98** [opentk/LearnOpenTK#88]
When resizing on MacOS, the rendered objects are divided by 2.

<img width="372" alt="macos" src="https://github.com/opentk/LearnOpenTK/assets/57635141/769f0f25-bb6c-4523-99b8-75cad4e3ce46">

The solution consists to use scale factor : 

        // Initialise the Scale Factor
        float scaleFactorX = 1.0f;
        float scaleFactorY = 1.0f;

And to identify it correctly on MacOS (2.0f on my Mac) during the OnLoad(): 

            // Get the Scale Factor of the Monitor
            this.TryGetCurrentMonitorScale(out scaleFactorX, out scaleFactorY);

Then the OnResize() needs to use it : 

            GL.Viewport(0, 0, (int)(Size.X * scaleFactorX), (int)(Size.Y * scaleFactorY));

With this method, the window once resized is displaying correctly the object : 

<img width="328" alt="macos-fix" src="https://github.com/opentk/LearnOpenTK/assets/57635141/58e818bb-efc6-40a7-b9db-5e4a3afc6c67">

**Comment by NogginBops** [comment]
The proper solution here I think is to use the `FramebufferSize` property and `OnFramebufferResize` properties that are new in 4.8.2
