### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tsnewer** [opentk/LearnOpenTK#98]
How to display vertices with coordinates greater than 1? Thanks！

**Comment by NogginBops** [comment]
You use a matrix to project vertices outside that range into the -1 to 1 range.
The tutorial goes over this in chapter 1.7-1.9
https://opentk.net/learn/chapter1/7-transformations.html

**Comment by tsnewer** [comment]
> You use a matrix to project vertices outside that range into the -1 to 1 range. The tutorial goes over this in chapter 1.7-1.9 https://opentk.net/learn/chapter1/7-transformations.html

Thanks so much.

**Comment by NogginBops** [comment]
I'm going to assume your question is answered and that this issue can be closed.
